server:
  servlet:
    context-path: /cliente-pet/api
    
spring:
  datasource:
    url: jdbc:h2:mem:demodb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    driverClassName: org.h2.Driver 
  
  h2:
    console:
      enabled: true
      path: /h2-console